import { createRouter } from '@tanstack/react-router'

// Import the generated route tree (will be generated by Vite plugin)
// The ! assertion tells TypeScript this import will exist at runtime
import { routeTree } from './routeTree.gen'

// Create router instance
export const router = createRouter({ 
  routeTree,
  defaultPreload: 'intent',
  defaultPreloadStaleTime: 0,
})

// Type augmentation for better TypeScript support
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}